### ISSUE TITLE
Display sites favicon on the left of article.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nilsbraden/ttrss-reader-fork#241]
```
I want to see sites favicon on the left of the article. Currently it shows atom 
or rss icon I think.
```

Original issue reported on code.google.com by `tomm...@gmail.com` on 17 May 2014 at 8:55

**Comment by MoriTanosuke** [comment]
I'd like to see this feature. The API method `getConfig` returns the field `icons_url` (usually `"feed-icons"`) which can be used with the base URL to fetch feeds.

Example URL for feed with ID 1234: https://example.com/path/to/ttrss/feed-icons/2977.ico

I'll have a look at the sourcecode to see if I can come up with a pull request.

**Comment by MoriTanosuke** [comment]
I got some time to waste this evening, and here's what I got at the moment:

![ttrss-favicons-draft1](https://user-images.githubusercontent.com/105346/36807235-b33ea054-1cc2-11e8-8777-775b8caf622a.PNG)

I thought about adding the favicon, if available, to the 2nd line of the articles. This kind of matches the web UI of *tt-rss*. I have to figure out the layout in `item_feedheadline.xml` to make it look a bit less ugly though.

My first attempt replaced the whole read/unread RSS icon with the favicon, but I noticed that some of my RSS feed do have pretty low-res favicons and having a large favicon will look bad. Having it in the 2nd row of the article list does not have this issue.

I want to clean up things a bit more, but if anyone is interested in my code (or I get lazy again), head over to my fork+branch at https://github.com/MoriTanosuke/ttrss-reader-fork/tree/feature/241-display-feed-icons

I'd appreciate some tips, because I'm not doing android development and things feel hacky.

**Comment by nilsbraden** [comment]
@MoriTanosuke  Sry for nmot answering for so long! I appreciate the work you put into this and am more than happy to merge this. The code looks good from a short look I just had at your branch. I think thea easiest way to merge it would be for you to provide a pull request here. Perhaps I'll try to get a little bit more space around the icon so it is centered vertically and has a small distance to the date information. But I think it looks good!
