### ISSUE TITLE
Tag new releases

### ISSUE THREAD

**Issue by rodrigoaguilera** [nilsbraden/ttrss-reader-fork#276]
I think this is the way f-droid builds the new releases.
I also opened an issue for the repo change.
https://gitlab.com/fdroid/fdroiddata/issues/191

Thanks for your work!

**Comment by nilsbraden** [comment]
Surprisingly the new IDE from Google (Android Studio) has no way of pushing tags. You can add them but have to push them manually by issueing "git push --tags". But since I just found out about this feature I'll probably create a script that does this and also pushes a Release to github when I add a Tag. Should I follow a special naming scheme for release tags?

**Comment by rodrigoaguilera** [comment]
I don't think it needs special naming but I feel like the following tags are not very semantical
1.82_2
1.81_(1)

Feel free to close this

**Comment by nilsbraden** [comment]
I just started using a script to tag and upload new releases. The latest release (v1.83.0) is the first one uploaded this. I'll keep the settings from this release on:

Tag: v{major}.{minor}.{build}
version_code: {major}{minor}{build}
Release Name: Release {tag}

The script will be added to the repository, I'll just fix some handling stuff and bugs beforehand. Do you have any more suggestions to support the build of fdroid?

**Comment by rodrigoaguilera** [comment]
I'm not an fdroid developer but I know that releases is going to help them. they are already aware of the way you tag the version to trigger the builds
