### ISSUE TITLE
f-droid and play store updates

### ISSUE THREAD

**Issue by 3ruce** [nilsbraden/ttrss-reader-fork#283]
I just got an upgrade notice to 1.83 from f-droid while there was nothing shown in the play store. Which is the most up to date or recommended place to install from?

**Comment by nilsbraden** [comment]
Generally it should not matter but the F-Droid repository is not under my control and I don't know how fast the new build is triggered by their build system so I cannot say for sure. This time I released a new version only here in the project repository and not in the play store. This was because I also had to test the release mechanism but didn't really want to push the release to all users which was a bad idea. I found some more bugs while using the 1.83 Version myself which I hope to be able to fix today. Next release will be on play store and probably at roughly the same time on F-Droid.

**Comment by 3ruce** [comment]
Cool, thanks, it was interesting that having installed from the play store, I had to uninstall and re-install from F-Droid to get the latest... I guess the repositories are inter-changable...
