### ISSUE TITLE
Some visual improvements?

### ISSUE THREAD

**Issue by Zarek999** [nilsbraden/ttrss-reader-fork#284]
Hello,
Great app, I like it.

I would only suggest you two visual improvements:

1- (perhaps a bug?) In the in-feed view (with the left panel with the feed entries and right panel with the entry content), when switching from an entry to another the right panel background become white for a short time instead of dark background (I use the Dark or Black theme).
This is not very pleasant, perhaps this can be changed in order to always keep the dark background :-)
I use the last version 1.84 from Android market and I'm not checked in previous versions.

2- The dark/black theme is good. But it could be better with a less important contrast between the background and the text. The text seems to be too white for me. An option in order to change the text color could be added? Or another theme with a text more grey or blue?
In your opinion would this be possible?

**Comment by eliseevmikhail** [comment]
Confirm

**Comment by nilsbraden** [comment]
3- Several UI elements have transparent background in android 5.x (especially Dialogs).

**Comment by nilsbraden** [comment]
About the theme and text colors:

@Zarek999 There are several useful tools for this but since I'm happy with the currently available options I'd suggest you choose the colors you want and I add the theme.

Tools: 
http://www.materialui.co/colors
https://www.materialpalette.com

You can have look at the file https://github.com/nilsbraden/ttrss-reader-fork/blob/master/ttrssreader/src/main/res/values/colors.xml to see what the necessary colors are.

**Comment by nilsbraden** [comment]
Slightly adjusted the color.

**Comment by Zarek999** [comment]
Thank you for your suggestions, but since I posted this message the themes finally suits me well.

And the bug of white background, this no happen anymore. This is a great improvement thank you.
