### ISSUE TITLE
Cannot open feed in category

### ISSUE THREAD

**Issue by prekz** [nilsbraden/ttrss-reader-fork#292]
In my TTRSS installation i use a couple of different categories. When i use the android TTRSS reader app it is not possible to open the feeds within a category.

**Comment by prekz** [comment]
In the screenshot below you see my categories and how much articles are available:
![screenshot_2015-05-18-12-15-07](https://cloud.githubusercontent.com/assets/10127852/7678846/ae84fea6-fd57-11e4-8004-979dcbc37c8a.png)

In the second screenshot i opened a feed and you cannot see the new article:
![screenshot_2015-05-18-12-15-14](https://cloud.githubusercontent.com/assets/10127852/7678864/dd4433ce-fd57-11e4-9058-700f4cb7cf73.png)

**Comment by nilsbraden** [comment]
Did you enable "Only cached articles" in the menu? This filters all articles that have no cached images in the source. To disable you need to press "Display all" in the menu. Please note that "Display all" may appear twice since the text is used for both of the following options:
- Display unread <-> Display all
- Only cached articles <-> Display all
