### ISSUE TITLE
Digest authentication no longer working.

### ISSUE THREAD

**Issue by virgoparna** [nilsbraden/ttrss-reader-fork#302]
After last update digest authentication no longer works. In changelog it says "Removed deprecated connector based on old apache libraries". Is that the reason? User interface still has "Use old connector...".

**Comment by nilsbraden** [comment]
You're right, the API has been removed from the support library since it was deprecated for a long time. I removed all calls to the old API from the project but forgot to remove the preference-entry. Just because I'm curious: Do you get the error "No trust anchor for certificate" when trying to connect to a server that expects digest auth?

**Comment by virgoparna** [comment]
Server does not use ssl. 
There is no error message in client. Is just continues showing progress until I close it. And server log shows, that every request is responded with 401 result code.

**Comment by nilsbraden** [comment]
Thank you!
