### ISSUE TITLE
Doesn't work with sandstorm.

### ISSUE THREAD

**Issue by petrukhnov** [nilsbraden/ttrss-reader-fork#344]
Doesn't work (Dolgov trial app works).
Tried:
Host: https://api-1afaa57ac327a243e9e49e045113fbe6.oasis.sandstorm.io
User: sandstorm
Password: RIt7H6ZT1CsZmu9Mt6zHcMucYK7wqEDsaKpRtJMYGbl

Also tried own grain.
Same 401 with /api, /api/, /api/index.php, http-auth, non-http auth.

ttrss 1.92.0
Tiny Tiny RSS
  * text in settings:  v1.15.3
  * text in grain description 1.9.0

**Comment by nilsbraden** [comment]
I don't understand. What is grain? What is sandstorm? What message do you get? Did you try the steps outlined in the Wiki ("Debugging")?

**Comment by R4mzy** [comment]
Just to add a little info since I've been watching for updates about this issue...
Sandstorm is a hosting platform/OS that runs "containerised" instances of web apps. A grain is their term for a container. Sandstorm provides a hosting service (called Oasis) for grains with a free tier that you can run a TT-RSS instance on (oasis.sandstorm.io). I have had the same problem as @petrukhnov with TTRSS-reader not able to connect to my Oasis Sandstorm. 

TTRSS-Reader doesn't seem to be able to connect to Sandstorm instances/grains of the TT-RSS server. Authentication fails with a 401 error in every attempt, doesn't seem to matter what options you select (HTTP-Auth or not) or what connection URL you use (plain URL or if you follow it with '/api', '/api/', '/api/index.php'...).

I don't find a "Debugging" page in the Wiki, only "Troubleshooting"... I'm setting up a test grain and getting CatLog and all that, & will try to get some logs out from there when I can...
