### ISSUE TITLE
Can not navigate up/down

### ISSUE THREAD

**Issue by MoriTanosuke** [nilsbraden/ttrss-reader-fork#370]
After updating to v1.93.0 I noticed that I can no longer swipe left/right to open articles, same when I try to use volume buttons or the navigation buttons.

I ran the app in an emulator and this is what *logcat* says when I try to navigate:

    03-18 08:25:49.568 18639-18639/org.ttrssreader W/System.err: context [anonymous] 1:775 attribute HYPHENATION isn't defined
    03-18 08:25:49.569 18639-18639/org.ttrssreader W/System.err: context [anonymous] 1:1151 attribute NOTE_TEMPLATE isn't defined
    03-18 08:25:49.570 18639-18639/org.ttrssreader W/System.err: context [anonymous] 1:1271 attribute NAVIGATION isn't defined

I don't know what that means, but maybe the behavior of the `WebView` Javascript interface changed?

I do hope that I did not break this with my changes to the UI in #368. 😢

**Comment by nilsbraden** [comment]
I slightly changed the behavior:

Icons are now loaded only from Data.java, JSONReader only parses JSON data and returns this. Data fetches everything else and inserts into DBHelper as before. Also I changed the Cursor since it didn't contain the Icon-Column in the result.

This works properly now but switching articles doesn't work anymore. I think that this hasn't anything to do with the pull request though.
