### ISSUE TITLE
Cannot login with password containing special characters

### ISSUE THREAD

**Issue by Berjou** [nilsbraden/ttrss-reader-fork#384]
Hi,

I installed your app today, and I struggled to connect to my server which keeps telling me that I provided incorrect username or password. The password was a random generated one containing special characters.

Then, I changed my password (which still a random generated one, but with only alphnumeric characters), and tried again. This solved the problem.

Please, note that it doesn't seem to be a server side configuration problem, since I was able to login without any problem with my old password with another app.

**Comment by MatthiasCzech** [comment]
Hi, 
I have the same problem.
I am using TTRSS-Reader 1.93.3 with Versions-Code: 1933

My TTRSS-Server is Runing behind a Traefik Reverse Proxy where I additionally could activate http basic authentification.
I used - and ! as special characters and made some tests
```
http | ttrss | connection
  X  |   X   | failed
  -  |   X   | failed
  X  |   -   | failed
  -  |   -   |  OK
```
x = special character used
- = only Letters and Numbers used

This shows that both password fields are effected or the general connection module.
It's not a big Issue because there is a workaround, but not all people are reading the issues, so it's frustrating when you are using a secure password and can not connect to your server.
But the problem was reported 7 months ago for the first time, please give this issue a higher priority because I don't want to use weak passwords with self hosted services.

**Comment by nilsbraden** [comment]
Not an issue anymore.
