### ISSUE TITLE
Stretched feed and menu view in 1.94.5

### ISSUE THREAD

**Issue by Areyus** [nilsbraden/ttrss-reader-fork#398]
Since the update to 1.94.5, all the list-like elements in the app seem to be stretched out. I have encountered this in the following elements:
* Category views (top level and list of feeds in categories)
* Article listing in feeds
* Settings menue
* Header/Action bar
* Probably as a side-effect, the unread-count indicators get blown up as well

This is not only a waste of screen space, but also quite a lot harder to read (at least in my opinion).

From my perception, article texts are not affected, but the action bar in the article view still is.
As as I can tell, this is probably either caused by displaying icons larger or (if the icons are autoscaled) from larger padding above and below text in lists.

Since I could not find anything about that in the changelog, I assume this is a bug. I remember that happening quite some time ago and it just went away some time later. That was probably about a year ago.

My device is a Huawei Nova 2 running Android 8, if this is of relevance, but I've seen the same look in screenshots from other recent issues like [here](https://github.com/nilsbraden/ttrss-reader-fork/issues/396).

**Comment by nilsbraden** [comment]
Yes it definitely changed and I'm not sure why but I guess one of the newer support libraries selects the spacing values from a different file for a different screen-size.

Nevertheless I'm against changing it because we are still 8dp per item below official recommendations, see the following comparison. I just assumed the AOSP settings dialog is following material design guidelines.
![overview list-sizes](https://user-images.githubusercontent.com/369563/65333892-9b2b7b80-dbc1-11e9-9ee1-b99ac73fdd1b.png)

I also compared all instances of the actionbar in various screenshots and there is no visible difference (except horizontal spacing which is not the point here and has different reasons).

**Comment by Areyus** [comment]
Thanks for the quick reply and the nice comparison.
I might be wrong about the header bars, maybe that feeling was wrong due to everything else beeing bigger.

I'll probably get used to it sooner or later, and the bigger spacing is probably OK for settings (since you're using those very differently than actual content) but I still don't feel that more "empty space per screen" is a good choice for a news feed. Might just be me, though, since I am not the biggest fan of the material design look and feel to begin with.

**Comment by nilsbraden** [comment]
I'll close this for now but I'm thinking about changing more things on the listview. The icon actually doesn't give any meaningful information and could be removed but then the list doesn't look appealing anymore. Maybe I can find a way of designing every list entry a bit so you can distinguish the entries better from each other and then the icon can be removed. Then we only need to make sure every entry is still far enough from the next so it can be easily pressed.
