### ISSUE TITLE
App does not show all unread articles.

### ISSUE THREAD

**Issue by marlluslustosa** [nilsbraden/ttrss-reader-fork#410]
My app does not show the total number of unread articles in my feed. For comparison, the browser (on desktop) shows that I have 16000 unread articles, and in a certain category I have 600 unread articles. However, by the app only shows that I have a total of 900 articles and in this category only 16 (15 articles from the present day and 1 from the previous day.).

I want it to show everyone, as well as through the browser, via desktop. I didn't see any date limit settings to retrieve unread articles.

It's possible?

**Comment by PrestonMcAfee** [comment]
I'm also setting a mismatch, and with much smaller numbers.  With 15 new articles, according to the web app, this app says 15 articles with 11 fresh (web says 15 fresh) and only shows the 11.

**Comment by nilsbraden** [comment]
@marlluslustosa I don't care about exact numbers since there is no point for me in knowing the exact amount in that order of magnitude. Does it make a big difference for you if its 16k or not? The articles are not stored on your phone anyway since you're not going to read 16k articles while browsing offline. At the time of creating this app the guy from Tiny Tiny RSS didn't care about creating a proper API that would allow me to load that many articles (he found it useless...) so I settled for downloading a few hundred (800? I don't remember right now...). 

@PrestonMcAfee within that range the numbers should normally be accurate. The range of hours an article is considered "fresh" is retrieved from the server once in a while but if you change it on the server it might take a day until it is published down to the app. It's considered "not important information" so only rarely refreshed. Also please provide screenshots of both, the app and the webinterface and some more information on how many articles are actually there.

**Comment by marlluslustosa** [comment]
Why do you assume there is no point in a user seeing how many articles he has not yet read?

16,000 may be a lot for some people, but it may not be for me. If I am a journalist or a user who needs to check the number of articles on my list? is it not worth to me?

Let go of your arrogance and say that your app does not support setting the maximum number of unread downloadable items as a parameter. It would be much simpler and more humble to be reasonable.

For the record, the feedme (https://github.com/seazon/feedme) has this feature.
And yes, I am using it.

**Comment by nilsbraden** [comment]
@marlluslustosa Please leave. I personally don't care about numbers and asked you to explain why the exact amount is necessary for you. No need to be rude but I got the message

**Comment by marlluslustosa** [comment]
You were rude!
Sorry if I was will, but I'm just a user trying to use your app or even improve it, developing something that can serve me, you or someone else.

Try to be considerate of people, otherwise you will end up as the maintainer of ttrss. Simply rude and arrogant.
