### ISSUE TITLE
Tasker plugin not working when launched from Automate

### ISSUE THREAD

**Issue by HunterZ** [nilsbraden/ttrss-reader-fork#411]
Using 1.94.6 (1946) installed from Google Play Store.

I had the Tasker plugin working from Automate on my Kindle Fire HD 10 2017, and am now trying to get it working on my Kindle Fire HD 10 2019 (Fire OS 7.3.1.1 based on Android 9.0).

I set it to show notifaction but to NOT cache images. When automate triggers the plugin, it reports immediate completion with "PluginInSetting ACTION_FIRE_SETTING: resultCode=-1" in the debug log, and no notification appears.

When I run the tt-rss app, it works fine and can update fine.

Any idea what's going wrong?

**Comment by nilsbraden** [comment]
The problem was introduced here https://github.com/nilsbraden/ttrss-reader-fork/commit/6c78d941cbe446be1997a46db86049501be7ed72 about 8 months ago and can easily be fixed. I encountered few other problems introduced with Android O, especially the new NotificationChannels which I also had to incorporate. It should work with the next update though.
