### ISSUE TITLE
white screen on app launch

### ISSUE THREAD

**Issue by 532910** [nilsbraden/ttrss-reader-fork#437]
White flash burns eyes:
![ScreenRecord-2020-12-12-02-53-48](https://user-images.githubusercontent.com/14617699/101965341-6459df00-3c25-11eb-98ce-a3bc7689767a.gif)
For example other apps like Orgzly, Binary Eye or Car Report has no flash.
v1.96.1, android 10

**Comment by nilsbraden** [comment]
What youre seeing is just the default background provided by android when nothing else is loaded yet. I'm not going to implement a splash-screen because they are annoying and not actually a solution, the just waste time.

So there are two things:
a) You setup your device to use a dark theme for everything. My Xiaomi does this and I get flashed with a dark screen, not much flashing going on there.
b) Someone takes the time to offload all initialization into background threads without breaking anything. Not exactly an easy task and probably not worth the effort.

**Comment by nilsbraden** [comment]
Ok forget about what I said earlier. I might have found an elegant solution by providing a default theme that is only applied for first launch.
